/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 staff-transformed.glb --transform 
Files: staff-transformed.glb [1.58MB] > E:\Varun P\Portfolio data\public\models\staff-transformed-transformed.glb [1.59MB] (-1%)
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Staff(props) {
  const { nodes, materials } = useGLTF(
    "/models/staff-transformed-transformed.glb"
  );
  const modelRef = useRef();

  useFrame(() => {
    modelRef.current.rotation.y += 0.007;
  });

  return (
    <group {...props} dispose={null} scale={[3, 3, 3]} position={[0, -2, 0]} ref={modelRef}>
      <mesh
        geometry={nodes.Wizard_Staff3_Wizard_Staff3_0.geometry}
        material={materials.Wizard_Staff3}
        position={[-0.041, 0.983, 0.768]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.Wizard_Staff2_Wizard_Staff2_0.geometry}
        material={materials.Wizard_Staff2}
        position={[-0.041, 0.983, 0.768]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.04}
      />
    </group>
  );
}

useGLTF.preload("/models/staff-transformed-transformed.glb");
